from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import date

class AirFinancialAuditQuery(BaseModel):
    waybill_number: Optional[str] = Field(None, description="运单号，支持输入多个，英文逗号隔开")
    flight_date_start: Optional[date] = Field(None, description="航班日期开始，格式：YYYY-MM-DD")
    flight_date_end: Optional[date] = Field(None, description="航班日期结束，格式：YYYY-MM-DD")
    agent_name: Optional[str] = Field(None, description="代理名称（仅对同行空运过滤）")
    destination: Optional[str] = Field(None, description="目的站（模糊搜索）")
    flight_number: Optional[str] = Field(None, description="航班号")
    audit_status: Optional[int] = Field(None, description="业务审核状态：0=未审, 1=暂存, 2=已审")
    financial_audit_status: Optional[int] = Field(None, description="财务审核状态：0=未审, 1=暂存, 2=已审")
    telegram_status: Optional[str] = Field(None, description="电报状态：有电报/无电报/全部")
    cca_status: Optional[str] = Field(None, description="CCA状态：有CCA/无CCA/全部")
    airline_type: Optional[str] = Field(None, description="航司类型：shenzhen_air / china_southern_air / peer_air")
    page: int = Field(1, ge=1, description="页码")
    pageSize: int = Field(10, ge=1, le=200, description="每页数量")

class PayableRequest(BaseModel):
    agent_name: Optional[str] = Field(None, description="代理名称(仅同行空运)")
    cargo_type: Optional[str] = Field(None, description="货物类型")
    billing_pieces: Optional[str] = Field(None, description="开单件数")
    billing_weight: Optional[str] = Field(None, description="开单重量")
    gate_pieces: Optional[str] = Field(None, description="过机件数")
    chargeable_weight: Optional[str] = Field(None, description="计费重量")
    freight_rate: Optional[str] = Field(None, description="主单费率")
    air_freight: Optional[str] = Field(None, description="主单运费")
    fuel_surcharge: Optional[str] = Field(None, description="燃油费用")
    transit_weight: Optional[str] = Field(None, description="过站重量")
    transit_fee: Optional[str] = Field(None, description="过站费用")
    cca_cost: Optional[str] = Field(None, description="CCA成本")
    telegraph_cost: Optional[str] = Field(None, description="电报成本(人工填写)")
    penalty_fee: Optional[str] = Field(None, description="违规罚款(人工填写)")
    packaging_fee: Optional[str] = Field(None, description="包装费")
    other_fees: Optional[str] = Field(None, description="其他费用")
    other_fee_remark: Optional[str] = Field(None, description="其他费用说明(人工填写)")
    door_pickup_company: Optional[str] = Field(None, description="上门提货单位")
    door_pickup_fee: Optional[str] = Field(None, description="上门提货费")
    delivery_company: Optional[str] = Field(None, description="派送单位")
    airport_pickup_fee: Optional[str] = Field(None, description="机场提货费")
    delivery_cost: Optional[str] = Field(None, description="派送成本")
    total_cost: Optional[str] = Field(None, description="成本合计")

class ReceivableRequest(BaseModel):
    waybill_number: Optional[str] = Field(None, description="运单号（新增接口时必传）")
    flight_date: Optional[str] = Field(None, description="航班日期")
    customer_name: Optional[str] = Field(None, description="客户名称")
    consignee_phone: Optional[str] = Field(None, description="收货电话")
    origin: Optional[str] = Field(None, description="始发站")
    airline: Optional[str] = Field(None, description="航空公司")
    flight_number: Optional[str] = Field(None, description="航班号")
    cargo_name: Optional[str] = Field(None, description="货物名称")
    pieces: Optional[str] = Field(None, description="件数")
    chargeable_weight: Optional[str] = Field(None, description="计费重量")
    freight_rate: Optional[str] = Field(None, description="费率")
    document_fee: Optional[str] = Field(None, description="制单费")
    packaging_fee: Optional[str] = Field(None, description="包装费")
    telegram_fee: Optional[str] = Field(None, description="电报费")
    telegram_code: Optional[str] = Field(None, description="电报号")
    other_fee_remark: Optional[str] = Field(None, description="其他费用说明(人工填写)")
    door_pickup_fee: Optional[str] = Field(None, description="上门提货费")
    airport_pickup_fee: Optional[str] = Field(None, description="机场提货费")
    carrier_deduction: Optional[str] = Field(None, description="承运扣款(人工填写)")
    total_amount: Optional[str] = Field(None, description="总金额")
    payment_method: Optional[str] = Field(None, description="付款方式")
    consignee: Optional[str] = Field(None, description="收货单位")
    destination: Optional[str] = Field(None, description="目的站")
    pickup_method: Optional[str] = Field(None, description="提货方式(人工填写)")
    weight: Optional[str] = Field(None, description="重量")
    freight: Optional[str] = Field(None, description="运费")
    cca: Optional[str] = Field(None, description="CCA")
    other_fees: Optional[str] = Field(None, description="其他费用")
    delivery_fee: Optional[str] = Field(None, description="派送费")
    collection_payment: Optional[str] = Field(None, description="代收货款(人工填写)")
    remark: Optional[str] = Field(None, description="备注(人工填写)")
    gross_profit: Optional[str] = Field(None, description="毛利")

class AirFinancialAuditCreateRequest(BaseModel):
    """空运财务审核新增请求"""
    payable: PayableRequest = Field(..., description="应付板块全部数据")
    receivable: ReceivableRequest = Field(..., description="应收板块全部数据（其中 waybill_number 和 airline 必传）")

class AirFinancialAuditDataUpsert(BaseModel):
    source_type: str = Field(..., description="来源类型: shenzhen_air / china_southern_air / peer_air")
    source_id: str = Field(..., description="来源主表ID")
    
    payable: Optional[PayableRequest] = Field(None, description="应付板块全部数据")
    receivable: Optional[ReceivableRequest] = Field(None, description="应收板块全部数据")

class PayableResponse(BaseModel):
    agent_name: Optional[str] = Field(None, description="代理名称(仅同行空运)")
    cargo_type: Optional[str] = Field(None, description="货物类型")
    billing_pieces: Optional[str] = Field(None, description="开单件数")
    billing_weight: Optional[str] = Field(None, description="开单重量")
    gate_pieces: Optional[str] = Field(None, description="过机件数")
    chargeable_weight: Optional[str] = Field(None, description="计费重量")
    freight_rate: Optional[str] = Field(None, description="主单费率")
    air_freight: Optional[str] = Field(None, description="主单运费")
    fuel_surcharge: Optional[str] = Field(None, description="燃油费用")
    transit_weight: Optional[str] = Field(None, description="过站重量")
    transit_fee: Optional[str] = Field(None, description="过站费用")
    cca_cost: Optional[str] = Field(None, description="CCA成本")
    telegraph_cost: Optional[str] = Field(None, description="电报成本(人工填写)")
    penalty_fee: Optional[str] = Field(None, description="违规罚款(人工填写)")
    packaging_fee: Optional[str] = Field(None, description="包装费")
    other_fees: Optional[str] = Field(None, description="其他费用")
    other_fee_remark: Optional[str] = Field(None, description="其他费用说明(人工填写)")
    door_pickup_company: Optional[str] = Field(None, description="上门提货单位")
    door_pickup_fee: Optional[str] = Field(None, description="上门提货费")
    delivery_company: Optional[str] = Field(None, description="派送单位")
    airport_pickup_fee: Optional[str] = Field(None, description="机场提货费")
    delivery_cost: Optional[str] = Field(None, description="派送成本")
    total_cost: Optional[str] = Field(None, description="成本合计")

class ReceivableResponse(BaseModel):
    waybill_number: Optional[str] = Field(None, description="运单号")
    flight_date: Optional[str] = Field(None, description="航班日期")
    customer_name: Optional[str] = Field(None, description="客户名称")
    consignee_phone: Optional[str] = Field(None, description="收货电话")
    origin: Optional[str] = Field(None, description="始发站")
    airline: Optional[str] = Field(None, description="航空公司")
    flight_number: Optional[str] = Field(None, description="航班号")
    cargo_name: Optional[str] = Field(None, description="货物名称")
    pieces: Optional[str] = Field(None, description="件数")
    chargeable_weight: Optional[str] = Field(None, description="计费重量")
    freight_rate: Optional[str] = Field(None, description="费率")
    document_fee: Optional[str] = Field(None, description="制单费")
    packaging_fee: Optional[str] = Field(None, description="包装费")
    telegram_fee: Optional[str] = Field(None, description="电报费")
    telegram_code: Optional[str] = Field(None, description="电报号")
    other_fee_remark: Optional[str] = Field(None, description="其他费用说明(人工填写)")
    door_pickup_fee: Optional[str] = Field(None, description="上门提货费")
    airport_pickup_fee: Optional[str] = Field(None, description="机场提货费")
    carrier_deduction: Optional[str] = Field(None, description="承运扣款(人工填写)")
    total_amount: Optional[str] = Field(None, description="总金额")
    payment_method: Optional[str] = Field(None, description="付款方式")
    consignee: Optional[str] = Field(None, description="收货单位")
    destination: Optional[str] = Field(None, description="目的站")
    pickup_method: Optional[str] = Field(None, description="提货方式(人工填写)")
    weight: Optional[str] = Field(None, description="重量")
    freight: Optional[str] = Field(None, description="运费")
    cca: Optional[str] = Field(None, description="CCA")
    other_fees: Optional[str] = Field(None, description="其他费用")
    delivery_fee: Optional[str] = Field(None, description="派送费")
    collection_payment: Optional[str] = Field(None, description="代收货款(人工填写)")
    remark: Optional[str] = Field(None, description="备注(人工填写)")
    gross_profit: Optional[str] = Field(None, description="毛利")

class ExtraData(BaseModel):
    pickup_point: Optional[str] = Field(None, description="提货点(机场中文名)")
    pickup_phone: Optional[str] = Field(None, description="提货电话")
    billing_time: Optional[str] = Field(None, description="计飞时间")
    Inquiry_hotline: Optional[str] = Field(None, description="查询热线(根据客户ID查询得到的联系电话)")

class AirFinancialAuditItemResponse(BaseModel):
    source_type: str = Field(..., description="来源类型: shenzhen_air / china_southern_air / peer_air")
    source_id: str = Field(..., description="来源主表ID")
    audit_status: int = Field(0, description="业务审核状态")
    financial_audit_status: int = Field(0, description="财务审核状态")
    flight_date: Optional[str] = Field(None, description="航班日期")
    customer_name: Optional[str] = Field(None, description="客户名称（通常为前端传入的客户ID）")
    actual_customer_name: Optional[str] = Field(None, description="真实客户名称（根据客户ID匹配得到）")
    agent_name: Optional[str] = Field(None, description="代理名称")
    airline: Optional[str] = Field(None, description="航空公司")
    waybill_number: Optional[str] = Field(None, description="运单号")
    origin: Optional[str] = Field(None, description="始发站")
    destination: Optional[str] = Field(None, description="目的站")
    flight_number: Optional[str] = Field(None, description="开单航班号")
    cargo_name: Optional[str] = Field(None, description="货物名称")
    billing_quantity: Optional[str] = Field(None, description="开单件数")
    billing_weight: Optional[str] = Field(None, description="开单重量")
    creator: Optional[str] = Field(None, description="制单人")
    creation_time: Optional[str] = Field(None, description="制单时间")
    payable: PayableResponse
    receivable: ReceivableResponse
    extra_data: Optional[ExtraData] = Field(None, description="额外数据，如提货点等")
