from sqlalchemy import Column, String, BigInteger, DateTime, Text, func
from app.database import Base
from app.utils.snowflake import generate_id
from app.utils.helpers import get_china_now

class ChinaSouthernAirApprovalData(Base):
    """南航订舱批复数据"""
    __tablename__ = "china_southern_air_approval_data"

    id = Column(BigInteger, primary_key=True, index=True, default=generate_id, comment="主键ID")
    flight_info = Column(String(255), index=True, nullable=True, comment="订舱航班")
    aircraft_type = Column(String(100), comment="机型")
    aircraft_no = Column(String(100), comment="飞机号")
    aircraft_limit = Column(String(100), comment="飞机号限制")
    planned_takeoff = Column(String(100), comment="计划起飞时间")
    expected_takeoff = Column(String(100), comment="预计起飞时间")
    flight_status = Column(String(100), comment="航班状态")
    waybill_number = Column(String(100), index=True, nullable=True, comment="运单号")
    agent_code = Column(String(100), comment="代理人编码")
    key_account_code = Column(String(100), comment="大客户编码")
    key_account_name = Column(String(255), comment="大客户名称")
    sales_channel = Column(String(100), comment="销售渠道")
    booking_no = Column(String(100), comment="订舱号")
    guarantee_level = Column(String(100), comment="保障等级")
    cabin_level = Column(String(100), comment="舱位等级")
    product_code = Column(String(100), comment="产品代码")
    booking_pieces = Column(String(100), comment="订舱件数")
    booking_weight = Column(String(100), comment="订舱重量")
    booking_volume = Column(String(100), comment="订舱体积")
    goods_name = Column(Text, comment="品名")
    commercial_danger_class = Column(String(100), comment="商用危险品类项")
    self_use_material_class = Column(String(100), comment="自用航材类项")
    aviation_oil_sample_class = Column(String(100), comment="航油样品类项")
    booking_uld = Column(String(100), comment="订舱ULD数量(板/箱)")
    booking_remark = Column(Text, comment="订舱备注")
    ad_remark = Column(Text, comment="AD备注")
    load_guidance = Column(Text, comment="装载指引")
    booking_routing = Column(String(100), comment="订舱航程")
    special_cargo_code = Column(String(100), comment="特种货物代码")
    billing_qty = Column(String(255), comment="制单数量(件数/重量/体积)")
    goods_qty = Column(String(255), comment="货物数量(件数/重量/体积)")
    actual_qty = Column(String(255), comment="实走数量(件数/重量/体积)")
    actual_flight = Column(String(255), comment="实走航班")
    container = Column(String(100), comment="所在容器")
    cargo_code = Column(String(100), comment="货物代码")
    routing_country = Column(String(100), comment="航程国别")
    department = Column(String(100), comment="部门")
    booking_time = Column(String(100), comment="订舱时间")
    ref_rate = Column(String(100), comment="参考运价")
    ref_freight = Column(String(100), comment="参考运费")
    currency = Column(String(100), comment="货币")
    other_fee = Column(String(100), comment="其他费用")
    total_control = Column(String(100), comment="总控控制")
    auto_approval = Column(String(100), comment="自动批复")
    level_auto_k = Column(String(100), comment="等级自动K舱")
    size = Column(String(100), comment="尺寸")
    settlement_discount_no = Column(String(100), comment="结算折扣号")
    customs_clearance_status = Column(String(100), comment="海关放行状态")
    single_window_check = Column(String(100), comment="单一窗口查验")
    chargeable_weight = Column(String(100), comment="计费重量")
    
    created_at = Column(DateTime, default=get_china_now, comment="记录创建时间")
    updated_at = Column(DateTime, default=get_china_now, onupdate=get_china_now, comment="记录更新时间")
