CREATE TABLE `shenzhen_air_approval_data` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `flight_number` varchar(50) DEFAULT NULL COMMENT '航班号',
  `flight_date` varchar(50) DEFAULT NULL COMMENT '航班日期',
  `aircraft_type` varchar(50) DEFAULT NULL COMMENT '机型',
  `departure_time` varchar(50) DEFAULT NULL COMMENT '起飞',
  `routing` varchar(100) DEFAULT NULL COMMENT '航程',
  `agent` varchar(100) DEFAULT NULL COMMENT '代理人',
  `f_booking` varchar(50) DEFAULT NULL COMMENT 'F订',
  `f_approval` varchar(50) DEFAULT NULL COMMENT 'F批',
  `c_booking` varchar(50) DEFAULT NULL COMMENT 'C订',
  `c_approval` varchar(50) DEFAULT NULL COMMENT 'C批',
  `other_booking` varchar(50) DEFAULT NULL COMMENT '其他订',
  `other_approval` varchar(50) DEFAULT NULL COMMENT '其他批',
  `status` varchar(50) DEFAULT NULL COMMENT '状态',
  `type` varchar(50) DEFAULT NULL COMMENT '类型',
  `control` varchar(50) DEFAULT NULL COMMENT '控制',
  `open_status` varchar(50) DEFAULT NULL COMMENT '开放',
  `remark` text COMMENT '备注',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `ix_shenzhen_air_approval_data_flight_number` (`flight_number`),
  KEY `ix_shenzhen_air_approval_data_flight_date` (`flight_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='深航订舱批复数据';
