CREATE TABLE IF NOT EXISTS `shenzhen_air_booking_exports` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `prefix` VARCHAR(20) DEFAULT NULL COMMENT '前缀',
    `waybill_number` VARCHAR(50) DEFAULT NULL COMMENT '单号',
    `waybill_status` VARCHAR(50) DEFAULT NULL COMMENT '运单状态',
    `creation_time` VARCHAR(50) DEFAULT NULL COMMENT '制单时间',
    `creator` VARCHAR(100) DEFAULT NULL COMMENT '制单人',
    `agent` VARCHAR(100) DEFAULT NULL COMMENT '代理人',
    `routing` VARCHAR(100) DEFAULT NULL COMMENT '航程',
    `flight_date` VARCHAR(50) DEFAULT NULL COMMENT '航班日期',
    `billing_flight` VARCHAR(50) DEFAULT NULL COMMENT '开单航班',
    `actual_flight` VARCHAR(50) DEFAULT NULL COMMENT '走货航班',
    `shipper` VARCHAR(255) DEFAULT NULL COMMENT '发货人',
    `consignee` VARCHAR(255) DEFAULT NULL COMMENT '收货人',
    `carrier` VARCHAR(100) DEFAULT NULL COMMENT '承运人',
    `storage_precautions` VARCHAR(255) DEFAULT NULL COMMENT '储运事项',
    `cargo_name` VARCHAR(255) DEFAULT NULL COMMENT '品名',
    `cabin` VARCHAR(50) DEFAULT NULL COMMENT '舱位',
    `quantity` VARCHAR(50) DEFAULT NULL COMMENT '件数',
    `weight` VARCHAR(50) DEFAULT NULL COMMENT '重量',
    `chargeable_weight` VARCHAR(50) DEFAULT NULL COMMENT '计费重量',
    `freight_rate` VARCHAR(50) DEFAULT NULL COMMENT '费率',
    `air_freight` VARCHAR(50) DEFAULT NULL COMMENT '航空运费',
    `fuel_surcharge` VARCHAR(50) DEFAULT NULL COMMENT '燃油费',
    `airport_management_fee` VARCHAR(50) DEFAULT NULL COMMENT '机管费',
    `total_amount` VARCHAR(50) DEFAULT NULL COMMENT '总金额',
    `price_code` VARCHAR(50) DEFAULT NULL COMMENT '运价代码',
    `handling_code` VARCHAR(50) DEFAULT NULL COMMENT '处理代码',
    `payment_method` VARCHAR(50) DEFAULT NULL COMMENT '支付方式',
    `waybill_type` VARCHAR(50) DEFAULT NULL COMMENT '运单类型',
    `quantity_difference` VARCHAR(50) DEFAULT NULL COMMENT '运输件数差额',
    `weight_difference` VARCHAR(50) DEFAULT NULL COMMENT '运输重量差额',
    `container` VARCHAR(255) DEFAULT NULL COMMENT '集装器',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    INDEX `idx_waybill_number` (`waybill_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='深航过机装机数据获取表';
