-- 创建费用登记台-费用信息登记表 (系统全局唯一记录)
CREATE TABLE IF NOT EXISTS `cost_registrations` (
    `id` bigint(20) NOT NULL COMMENT '登记模版记录ID',
    -- (1) 货主委托信息
    `create_time` datetime DEFAULT NULL COMMENT '制单时间',
    `internal_doc_id` varchar(100) DEFAULT NULL COMMENT '内部单据ID',
    `warehouse_entry_date` date DEFAULT NULL COMMENT '进仓日期',
    `customer_name` varchar(100) DEFAULT NULL COMMENT '客户名称',
    `origin_destination` varchar(100) DEFAULT NULL COMMENT '始发站-目的站',
    `customs_declaration` varchar(50) DEFAULT NULL COMMENT '报关',
    `bill_of_lading` varchar(100) DEFAULT NULL COMMENT '提单',
    `flight_date` date DEFAULT NULL COMMENT '航班日期',
    `flight_no` varchar(50) DEFAULT NULL COMMENT '航班号',
    `flight_doc_no` varchar(100) DEFAULT NULL COMMENT '航班单号',
    `pieces` int(11) DEFAULT NULL COMMENT '件数',
    `actual_weight` decimal(10,2) DEFAULT NULL COMMENT '实际重量',
    `chargeable_weight` decimal(10,2) DEFAULT NULL COMMENT '计费重量',
    `volume` decimal(10,3) DEFAULT NULL COMMENT '体积',
    `first_leg_weight` decimal(10,2) DEFAULT NULL COMMENT '一程重量',
    `agent` varchar(100) DEFAULT NULL COMMENT '代理',
    `remark` text DEFAULT NULL COMMENT '备注',
    -- (2) 应收款项
    `unit_price` decimal(10,2) DEFAULT NULL COMMENT '单价',
    `receivable_freight` decimal(10,2) DEFAULT NULL COMMENT '运费',
    `receivable_lading_info_fee` decimal(10,2) DEFAULT NULL COMMENT '提单费/信息录入费',
    `receivable_split_offset_telex_fee` decimal(10,2) DEFAULT NULL COMMENT '分单费/抵账费/电报费',
    `receivable_customs_fee` decimal(10,2) DEFAULT NULL COMMENT '报关费',
    `receivable_continuation_sheet_fee` decimal(10,2) DEFAULT NULL COMMENT '续页费',
    `receivable_customs_inspection_fee` decimal(10,2) DEFAULT NULL COMMENT '海关查验费',
    `receivable_magnetic_security_fee` decimal(10,2) DEFAULT NULL COMMENT '磁检费/安检费',
    `receivable_tc_express_fee` decimal(10,2) DEFAULT NULL COMMENT 'TC操作费/快件中心过站费',
    `receivable_warehouse_ground_fee` decimal(10,2) DEFAULT NULL COMMENT '前置仓/国际货站地面费',
    `receivable_doc_make_fee` decimal(10,2) DEFAULT NULL COMMENT '制单费',
    `receivable_doc_split_fee` decimal(10,2) DEFAULT NULL COMMENT '制单分单费',
    `receivable_skid_fee` decimal(10,2) DEFAULT NULL COMMENT '垫板费',
    `receivable_pallet_packing_fee` decimal(10,2) DEFAULT NULL COMMENT '打板/装箱费',
    `receivable_probe_fee` decimal(10,2) DEFAULT NULL COMMENT '探板费',
    `receivable_consumables_fee` decimal(10,2) DEFAULT NULL COMMENT '耗材费',
    `receivable_first_leg_fee` decimal(10,2) DEFAULT NULL COMMENT '一程费用',
    `receivable_total` decimal(10,2) DEFAULT NULL COMMENT '应收合计',
    -- (3) 应付款项 - [1] 国际空运信息
    `pay_intl_air_subtotal` decimal(10,2) DEFAULT NULL COMMENT '国际空运-应付小计',
    `pay_intl_air_outsource_unit` varchar(100) DEFAULT NULL COMMENT '国际空运-外发单位',
    `pay_intl_air_origin` varchar(50) DEFAULT NULL COMMENT '国际空运-始发站',
    `pay_intl_air_destination` varchar(50) DEFAULT NULL COMMENT '国际空运-到达站',
    `pay_intl_air_flight_doc_no` varchar(100) DEFAULT NULL COMMENT '国际空运-航班单号/航空单号',
    `pay_intl_air_flight_no` varchar(50) DEFAULT NULL COMMENT '国际空运-航班号',
    `pay_intl_air_flight_date` date DEFAULT NULL COMMENT '国际空运-航班日期',
    `pay_intl_air_pieces` int(11) DEFAULT NULL COMMENT '国际空运-件数',
    `pay_intl_air_weight` decimal(10,2) DEFAULT NULL COMMENT '国际空运-重量',
    `pay_intl_air_volume` decimal(10,3) DEFAULT NULL COMMENT '国际空运-体积',
    `pay_intl_air_chargeable_weight` decimal(10,2) DEFAULT NULL COMMENT '国际空运-计费重量',
    `pay_intl_air_rate` decimal(10,2) DEFAULT NULL COMMENT '国际空运-费率',
    `pay_intl_air_freight` decimal(10,2) DEFAULT NULL COMMENT '国际空运-运费',
    `pay_intl_air_lading_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-提单费',
    `pay_intl_air_split_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-分单',
    `pay_intl_air_borrow_magnetic_fuel_pickup_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-借单费/磁检费/燃油费/国内提货费',
    `pay_intl_air_tc_network_disposal_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-TC费/入网费/国际处置费',
    `pay_intl_air_customs_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-报关费',
    `pay_intl_air_continuation_sheet_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-续页费',
    `pay_intl_air_consumables_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-耗材费',
    `pay_intl_air_front_warehouse` decimal(10,2) DEFAULT NULL COMMENT '国际空运-前置仓',
    `pay_intl_air_other_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-其他费用',
    `pay_intl_air_remark` text DEFAULT NULL COMMENT '国际空运-备注',
    -- (3) 应付款项 - [2] 汽运信息
    `pay_trucking_subtotal` decimal(10,2) DEFAULT NULL COMMENT '汽运-应付小计',
    `pay_trucking_date` date DEFAULT NULL COMMENT '汽运-托运日期',
    `pay_trucking_outsource_unit` varchar(100) DEFAULT NULL COMMENT '汽运-外发单位',
    `pay_trucking_pieces` int(11) DEFAULT NULL COMMENT '汽运-件数',
    `pay_trucking_weight` decimal(10,2) DEFAULT NULL COMMENT '汽运-重量',
    `pay_trucking_volume` decimal(10,3) DEFAULT NULL COMMENT '汽运-体积',
    `pay_trucking_unit_price` decimal(10,2) DEFAULT NULL COMMENT '汽运-单价',
    `pay_trucking_freight` decimal(10,2) DEFAULT NULL COMMENT '汽运-运费',
    `pay_trucking_doc_fee` decimal(10,2) DEFAULT NULL COMMENT '汽运-制单费',
    `pay_trucking_other_fee` decimal(10,2) DEFAULT NULL COMMENT '汽运-其他费用',
    `pay_trucking_remark` text DEFAULT NULL COMMENT '汽运-备注',
    -- (3) 应付款项 - [3] 国内空运信息
    `pay_dom_air_subtotal` decimal(10,2) DEFAULT NULL COMMENT '国内空运-应付小计',
    `pay_dom_air_date` date DEFAULT NULL COMMENT '国内空运-托运日期',
    `pay_dom_air_outsource_unit` varchar(100) DEFAULT NULL COMMENT '国内空运-外发单位',
    `pay_dom_air_origin` varchar(50) DEFAULT NULL COMMENT '国内空运-始发站',
    `pay_dom_air_destination` varchar(50) DEFAULT NULL COMMENT '国内空运-到达站',
    `pay_dom_air_airline` varchar(100) DEFAULT NULL COMMENT '国内空运-航空公司',
    `pay_dom_air_airline_unit` varchar(100) DEFAULT NULL COMMENT '国内空运-航空单位',
    `pay_dom_air_flight_doc_no` varchar(100) DEFAULT NULL COMMENT '国内空运-航空单号',
    `pay_dom_air_flight_no` varchar(50) DEFAULT NULL COMMENT '国内空运-航班号',
    `pay_dom_air_flight_date` date DEFAULT NULL COMMENT '国内空运-航班日期',
    `pay_dom_air_pieces` int(11) DEFAULT NULL COMMENT '国内空运-件数',
    `pay_dom_air_weight` decimal(10,2) DEFAULT NULL COMMENT '国内空运-重量',
    `pay_dom_air_chargeable_weight` decimal(10,2) DEFAULT NULL COMMENT '国内空运-计费重量',
    `pay_dom_air_rate` decimal(10,2) DEFAULT NULL COMMENT '国内空运-费率',
    `pay_dom_air_freight` decimal(10,2) DEFAULT NULL COMMENT '国内空运-运费',
    `pay_dom_air_other_fee` decimal(10,2) DEFAULT NULL COMMENT '国内空运-其他费用',
    `pay_dom_air_remark` text DEFAULT NULL COMMENT '国内空运-备注',
    -- (3) 应付款项 - [4] 报关信息
    `pay_customs_subtotal` decimal(10,2) DEFAULT NULL COMMENT '报关-应付小计',
    `pay_customs_date` date DEFAULT NULL COMMENT '报关-报关日期',
    `pay_customs_agent` varchar(100) DEFAULT NULL COMMENT '报关-报关代理',
    `pay_customs_fee` decimal(10,2) DEFAULT NULL COMMENT '报关-报关费',
    `pay_customs_continuation_sheet_fee` decimal(10,2) DEFAULT NULL COMMENT '报关-续页费',
    `pay_customs_inspection_delete_fee` decimal(10,2) DEFAULT NULL COMMENT '报关-查验费/删单费',
    `pay_customs_other_fee` decimal(10,2) DEFAULT NULL COMMENT '报关-其他费用',
    `pay_customs_remark` text DEFAULT NULL COMMENT '报关-备注',
    -- (3) 应付款项 - [5] 地面操作信息
    `pay_ground_subtotal` decimal(10,2) DEFAULT NULL COMMENT '地面操作-应付小计',
    `pay_ground_date` date DEFAULT NULL COMMENT '地面操作-托运日期',
    `pay_ground_outsource_unit` varchar(100) DEFAULT NULL COMMENT '地面操作-外发单位',
    `pay_ground_chargeable_weight` decimal(10,2) DEFAULT NULL COMMENT '地面操作-计费重量',
    `pay_ground_rate` decimal(10,2) DEFAULT NULL COMMENT '地面操作-费率',
    `pay_ground_freight` decimal(10,2) DEFAULT NULL COMMENT '地面操作-运费',
    `pay_ground_lading_express_fee` decimal(10,2) DEFAULT NULL COMMENT '地面操作-提单费/快件处置费',
    `pay_ground_security_customs_fee` decimal(10,2) DEFAULT NULL COMMENT '地面操作-安检费/报关费',
    `pay_ground_pallet_exit_fee` decimal(10,2) DEFAULT NULL COMMENT '地面操作-打板费/退场费',
    `pay_ground_other_fee` decimal(10,2) DEFAULT NULL COMMENT '地面操作-其他费用',
    `pay_ground_remark` text DEFAULT NULL COMMENT '地面操作-备注',
    -- (3) 应付款项 - 合计
    `pay_total` decimal(10,2) DEFAULT NULL COMMENT '应付合计',
    -- (4) 折让信息
    `discount_person` varchar(100) DEFAULT NULL COMMENT '折让人员',
    `discount_fee` decimal(10,2) DEFAULT NULL COMMENT '折让费',
    -- (5) 销售提成
    `salesperson` varchar(100) DEFAULT NULL COMMENT '业务员',
    `commission_amount` decimal(10,2) DEFAULT NULL COMMENT '提成金额',
    -- (6) 经营信息
    `profit` decimal(10,2) DEFAULT NULL COMMENT '利润',
    `profit_margin` decimal(10,2) DEFAULT NULL COMMENT '利润率',
    -- 系统审计
    `created_at` datetime NOT NULL COMMENT '创建时间',
    `updated_at` datetime NOT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='费用信息登记表（系统全局唯一记录）';


-- 创建费用登记台-费用单据明细表
CREATE TABLE IF NOT EXISTS `cost_consignments` (
    `id` bigint(20) NOT NULL COMMENT '费用单据明细ID',
    -- (1) 货主委托信息
    `create_time` datetime DEFAULT NULL COMMENT '制单时间',
    `internal_doc_id` varchar(100) DEFAULT NULL COMMENT '内部单据ID',
    `warehouse_entry_date` date DEFAULT NULL COMMENT '进仓日期',
    `customer_name` varchar(100) DEFAULT NULL COMMENT '客户名称',
    `origin_destination` varchar(100) DEFAULT NULL COMMENT '始发站-目的站',
    `customs_declaration` varchar(50) DEFAULT NULL COMMENT '报关',
    `bill_of_lading` varchar(100) DEFAULT NULL COMMENT '提单',
    `flight_date` date DEFAULT NULL COMMENT '航班日期',
    `flight_no` varchar(50) DEFAULT NULL COMMENT '航班号',
    `flight_doc_no` varchar(100) DEFAULT NULL COMMENT '航班单号',
    `pieces` int(11) DEFAULT NULL COMMENT '件数',
    `actual_weight` decimal(10,2) DEFAULT NULL COMMENT '实际重量',
    `chargeable_weight` decimal(10,2) DEFAULT NULL COMMENT '计费重量',
    `volume` decimal(10,3) DEFAULT NULL COMMENT '体积',
    `first_leg_weight` decimal(10,2) DEFAULT NULL COMMENT '一程重量',
    `agent` varchar(100) DEFAULT NULL COMMENT '代理',
    `remark` text DEFAULT NULL COMMENT '备注',
    -- (2) 应收款项
    `unit_price` decimal(10,2) DEFAULT NULL COMMENT '单价',
    `receivable_freight` decimal(10,2) DEFAULT NULL COMMENT '运费',
    `receivable_lading_info_fee` decimal(10,2) DEFAULT NULL COMMENT '提单费/信息录入费',
    `receivable_split_offset_telex_fee` decimal(10,2) DEFAULT NULL COMMENT '分单费/抵账费/电报费',
    `receivable_customs_fee` decimal(10,2) DEFAULT NULL COMMENT '报关费',
    `receivable_continuation_sheet_fee` decimal(10,2) DEFAULT NULL COMMENT '续页费',
    `receivable_customs_inspection_fee` decimal(10,2) DEFAULT NULL COMMENT '海关查验费',
    `receivable_magnetic_security_fee` decimal(10,2) DEFAULT NULL COMMENT '磁检费/安检费',
    `receivable_tc_express_fee` decimal(10,2) DEFAULT NULL COMMENT 'TC操作费/快件中心过站费',
    `receivable_warehouse_ground_fee` decimal(10,2) DEFAULT NULL COMMENT '前置仓/国际货站地面费',
    `receivable_doc_make_fee` decimal(10,2) DEFAULT NULL COMMENT '制单费',
    `receivable_doc_split_fee` decimal(10,2) DEFAULT NULL COMMENT '制单分单费',
    `receivable_skid_fee` decimal(10,2) DEFAULT NULL COMMENT '垫板费',
    `receivable_pallet_packing_fee` decimal(10,2) DEFAULT NULL COMMENT '打板/装箱费',
    `receivable_probe_fee` decimal(10,2) DEFAULT NULL COMMENT '探板费',
    `receivable_consumables_fee` decimal(10,2) DEFAULT NULL COMMENT '耗材费',
    `receivable_first_leg_fee` decimal(10,2) DEFAULT NULL COMMENT '一程费用',
    `receivable_total` decimal(10,2) DEFAULT NULL COMMENT '应收合计',
    -- (3) 应付款项 - [1] 国际空运信息
    `pay_intl_air_subtotal` decimal(10,2) DEFAULT NULL COMMENT '国际空运-应付小计',
    `pay_intl_air_outsource_unit` varchar(100) DEFAULT NULL COMMENT '国际空运-外发单位',
    `pay_intl_air_origin` varchar(50) DEFAULT NULL COMMENT '国际空运-始发站',
    `pay_intl_air_destination` varchar(50) DEFAULT NULL COMMENT '国际空运-到达站',
    `pay_intl_air_flight_doc_no` varchar(100) DEFAULT NULL COMMENT '国际空运-航班单号/航空单号',
    `pay_intl_air_flight_no` varchar(50) DEFAULT NULL COMMENT '国际空运-航班号',
    `pay_intl_air_flight_date` date DEFAULT NULL COMMENT '国际空运-航班日期',
    `pay_intl_air_pieces` int(11) DEFAULT NULL COMMENT '国际空运-件数',
    `pay_intl_air_weight` decimal(10,2) DEFAULT NULL COMMENT '国际空运-重量',
    `pay_intl_air_volume` decimal(10,3) DEFAULT NULL COMMENT '国际空运-体积',
    `pay_intl_air_chargeable_weight` decimal(10,2) DEFAULT NULL COMMENT '国际空运-计费重量',
    `pay_intl_air_rate` decimal(10,2) DEFAULT NULL COMMENT '国际空运-费率',
    `pay_intl_air_freight` decimal(10,2) DEFAULT NULL COMMENT '国际空运-运费',
    `pay_intl_air_lading_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-提单费',
    `pay_intl_air_split_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-分单',
    `pay_intl_air_borrow_magnetic_fuel_pickup_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-借单费/磁检费/燃油费/国内提货费',
    `pay_intl_air_tc_network_disposal_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-TC费/入网费/国际处置费',
    `pay_intl_air_customs_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-报关费',
    `pay_intl_air_continuation_sheet_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-续页费',
    `pay_intl_air_consumables_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-耗材费',
    `pay_intl_air_front_warehouse` decimal(10,2) DEFAULT NULL COMMENT '国际空运-前置仓',
    `pay_intl_air_other_fee` decimal(10,2) DEFAULT NULL COMMENT '国际空运-其他费用',
    `pay_intl_air_remark` text DEFAULT NULL COMMENT '国际空运-备注',
    -- (3) 应付款项 - [2] 汽运信息
    `pay_trucking_subtotal` decimal(10,2) DEFAULT NULL COMMENT '汽运-应付小计',
    `pay_trucking_date` date DEFAULT NULL COMMENT '汽运-托运日期',
    `pay_trucking_outsource_unit` varchar(100) DEFAULT NULL COMMENT '汽运-外发单位',
    `pay_trucking_pieces` int(11) DEFAULT NULL COMMENT '汽运-件数',
    `pay_trucking_weight` decimal(10,2) DEFAULT NULL COMMENT '汽运-重量',
    `pay_trucking_volume` decimal(10,3) DEFAULT NULL COMMENT '汽运-体积',
    `pay_trucking_unit_price` decimal(10,2) DEFAULT NULL COMMENT '汽运-单价',
    `pay_trucking_freight` decimal(10,2) DEFAULT NULL COMMENT '汽运-运费',
    `pay_trucking_doc_fee` decimal(10,2) DEFAULT NULL COMMENT '汽运-制单费',
    `pay_trucking_other_fee` decimal(10,2) DEFAULT NULL COMMENT '汽运-其他费用',
    `pay_trucking_remark` text DEFAULT NULL COMMENT '汽运-备注',
    -- (3) 应付款项 - [3] 国内空运信息
    `pay_dom_air_subtotal` decimal(10,2) DEFAULT NULL COMMENT '国内空运-应付小计',
    `pay_dom_air_date` date DEFAULT NULL COMMENT '国内空运-托运日期',
    `pay_dom_air_outsource_unit` varchar(100) DEFAULT NULL COMMENT '国内空运-外发单位',
    `pay_dom_air_origin` varchar(50) DEFAULT NULL COMMENT '国内空运-始发站',
    `pay_dom_air_destination` varchar(50) DEFAULT NULL COMMENT '国内空运-到达站',
    `pay_dom_air_airline` varchar(100) DEFAULT NULL COMMENT '国内空运-航空公司',
    `pay_dom_air_airline_unit` varchar(100) DEFAULT NULL COMMENT '国内空运-航空单位',
    `pay_dom_air_flight_doc_no` varchar(100) DEFAULT NULL COMMENT '国内空运-航空单号',
    `pay_dom_air_flight_no` varchar(50) DEFAULT NULL COMMENT '国内空运-航班号',
    `pay_dom_air_flight_date` date DEFAULT NULL COMMENT '国内空运-航班日期',
    `pay_dom_air_pieces` int(11) DEFAULT NULL COMMENT '国内空运-件数',
    `pay_dom_air_weight` decimal(10,2) DEFAULT NULL COMMENT '国内空运-重量',
    `pay_dom_air_chargeable_weight` decimal(10,2) DEFAULT NULL COMMENT '国内空运-计费重量',
    `pay_dom_air_rate` decimal(10,2) DEFAULT NULL COMMENT '国内空运-费率',
    `pay_dom_air_freight` decimal(10,2) DEFAULT NULL COMMENT '国内空运-运费',
    `pay_dom_air_other_fee` decimal(10,2) DEFAULT NULL COMMENT '国内空运-其他费用',
    `pay_dom_air_remark` text DEFAULT NULL COMMENT '国内空运-备注',
    -- (3) 应付款项 - [4] 报关信息
    `pay_customs_subtotal` decimal(10,2) DEFAULT NULL COMMENT '报关-应付小计',
    `pay_customs_date` date DEFAULT NULL COMMENT '报关-报关日期',
    `pay_customs_agent` varchar(100) DEFAULT NULL COMMENT '报关-报关代理',
    `pay_customs_fee` decimal(10,2) DEFAULT NULL COMMENT '报关-报关费',
    `pay_customs_continuation_sheet_fee` decimal(10,2) DEFAULT NULL COMMENT '报关-续页费',
    `pay_customs_inspection_delete_fee` decimal(10,2) DEFAULT NULL COMMENT '报关-查验费/删单费',
    `pay_customs_other_fee` decimal(10,2) DEFAULT NULL COMMENT '报关-其他费用',
    `pay_customs_remark` text DEFAULT NULL COMMENT '报关-备注',
    -- (3) 应付款项 - [5] 地面操作信息
    `pay_ground_subtotal` decimal(10,2) DEFAULT NULL COMMENT '地面操作-应付小计',
    `pay_ground_date` date DEFAULT NULL COMMENT '地面操作-托运日期',
    `pay_ground_outsource_unit` varchar(100) DEFAULT NULL COMMENT '地面操作-外发单位',
    `pay_ground_chargeable_weight` decimal(10,2) DEFAULT NULL COMMENT '地面操作-计费重量',
    `pay_ground_rate` decimal(10,2) DEFAULT NULL COMMENT '地面操作-费率',
    `pay_ground_freight` decimal(10,2) DEFAULT NULL COMMENT '地面操作-运费',
    `pay_ground_lading_express_fee` decimal(10,2) DEFAULT NULL COMMENT '地面操作-提单费/快件处置费',
    `pay_ground_security_customs_fee` decimal(10,2) DEFAULT NULL COMMENT '地面操作-安检费/报关费',
    `pay_ground_pallet_exit_fee` decimal(10,2) DEFAULT NULL COMMENT '地面操作-打板费/退场费',
    `pay_ground_other_fee` decimal(10,2) DEFAULT NULL COMMENT '地面操作-其他费用',
    `pay_ground_remark` text DEFAULT NULL COMMENT '地面操作-备注',
    -- (3) 应付款项 - 合计
    `pay_total` decimal(10,2) DEFAULT NULL COMMENT '应付合计',
    -- (4) 折让信息
    `discount_person` varchar(100) DEFAULT NULL COMMENT '折让人员',
    `discount_fee` decimal(10,2) DEFAULT NULL COMMENT '折让费',
    -- (5) 销售提成
    `salesperson` varchar(100) DEFAULT NULL COMMENT '业务员',
    `commission_amount` decimal(10,2) DEFAULT NULL COMMENT '提成金额',
    -- (6) 经营信息
    `profit` decimal(10,2) DEFAULT NULL COMMENT '利润',
    `profit_margin` decimal(10,2) DEFAULT NULL COMMENT '利润率',
    -- 系统审计
    `creator_id` bigint(20) DEFAULT NULL COMMENT '创建者ID',
    `created_at` datetime NOT NULL COMMENT '创建时间',
    `updated_at` datetime NOT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_warehouse_entry_date` (`warehouse_entry_date`),
    KEY `idx_customer_name` (`customer_name`),
    KEY `idx_agent` (`agent`),
    KEY `idx_flight_doc_no` (`flight_doc_no`),
    KEY `idx_flight_no` (`flight_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='费用单据明细表';
