-- 建表: 南航订舱批复数据表 (china_southern_air_approval_data)
CREATE TABLE `china_southern_air_approval_data` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `flight_info` VARCHAR(255) DEFAULT NULL COMMENT '订舱航班',
  `aircraft_type` VARCHAR(100) DEFAULT NULL COMMENT '机型',
  `aircraft_no` VARCHAR(100) DEFAULT NULL COMMENT '飞机号',
  `aircraft_limit` VARCHAR(100) DEFAULT NULL COMMENT '飞机号限制',
  `planned_takeoff` VARCHAR(100) DEFAULT NULL COMMENT '计划起飞时间',
  `expected_takeoff` VARCHAR(100) DEFAULT NULL COMMENT '预计起飞时间',
  `flight_status` VARCHAR(100) DEFAULT NULL COMMENT '航班状态',
  `waybill_number` VARCHAR(100) DEFAULT NULL COMMENT '运单号',
  `agent_code` VARCHAR(100) DEFAULT NULL COMMENT '代理人编码',
  `key_account_code` VARCHAR(100) DEFAULT NULL COMMENT '大客户编码',
  `key_account_name` VARCHAR(255) DEFAULT NULL COMMENT '大客户名称',
  `sales_channel` VARCHAR(100) DEFAULT NULL COMMENT '销售渠道',
  `booking_no` VARCHAR(100) DEFAULT NULL COMMENT '订舱号',
  `guarantee_level` VARCHAR(100) DEFAULT NULL COMMENT '保障等级',
  `cabin_level` VARCHAR(100) DEFAULT NULL COMMENT '舱位等级',
  `product_code` VARCHAR(100) DEFAULT NULL COMMENT '产品代码',
  `booking_pieces` VARCHAR(100) DEFAULT NULL COMMENT '订舱件数',
  `booking_weight` VARCHAR(100) DEFAULT NULL COMMENT '订舱重量',
  `booking_volume` VARCHAR(100) DEFAULT NULL COMMENT '订舱体积',
  `goods_name` TEXT DEFAULT NULL COMMENT '品名',
  `commercial_danger_class` VARCHAR(100) DEFAULT NULL COMMENT '商用危险品类项',
  `self_use_material_class` VARCHAR(100) DEFAULT NULL COMMENT '自用航材类项',
  `aviation_oil_sample_class` VARCHAR(100) DEFAULT NULL COMMENT '航油样品类项',
  `booking_uld` VARCHAR(100) DEFAULT NULL COMMENT '订舱ULD数量(板/箱)',
  `booking_remark` TEXT DEFAULT NULL COMMENT '订舱备注',
  `ad_remark` TEXT DEFAULT NULL COMMENT 'AD备注',
  `load_guidance` TEXT DEFAULT NULL COMMENT '装载指引',
  `booking_routing` VARCHAR(100) DEFAULT NULL COMMENT '订舱航程',
  `special_cargo_code` VARCHAR(100) DEFAULT NULL COMMENT '特种货物代码',
  `billing_qty` VARCHAR(255) DEFAULT NULL COMMENT '制单数量(件数/重量/体积)',
  `goods_qty` VARCHAR(255) DEFAULT NULL COMMENT '货物数量(件数/重量/体积)',
  `actual_qty` VARCHAR(255) DEFAULT NULL COMMENT '实走数量(件数/重量/体积)',
  `actual_flight` VARCHAR(255) DEFAULT NULL COMMENT '实走航班',
  `container` VARCHAR(100) DEFAULT NULL COMMENT '所在容器',
  `cargo_code` VARCHAR(100) DEFAULT NULL COMMENT '货物代码',
  `routing_country` VARCHAR(100) DEFAULT NULL COMMENT '航程国别',
  `department` VARCHAR(100) DEFAULT NULL COMMENT '部门',
  `booking_time` VARCHAR(100) DEFAULT NULL COMMENT '订舱时间',
  `ref_rate` VARCHAR(100) DEFAULT NULL COMMENT '参考运价',
  `ref_freight` VARCHAR(100) DEFAULT NULL COMMENT '参考运费',
  `currency` VARCHAR(100) DEFAULT NULL COMMENT '货币',
  `other_fee` VARCHAR(100) DEFAULT NULL COMMENT '其他费用',
  `total_control` VARCHAR(100) DEFAULT NULL COMMENT '总控控制',
  `auto_approval` VARCHAR(100) DEFAULT NULL COMMENT '自动批复',
  `level_auto_k` VARCHAR(100) DEFAULT NULL COMMENT '等级自动K舱',
  `size` VARCHAR(100) DEFAULT NULL COMMENT '尺寸',
  `settlement_discount_no` VARCHAR(100) DEFAULT NULL COMMENT '结算折扣号',
  `customs_clearance_status` VARCHAR(100) DEFAULT NULL COMMENT '海关放行状态',
  `single_window_check` VARCHAR(100) DEFAULT NULL COMMENT '单一窗口查验',
  `chargeable_weight` VARCHAR(100) DEFAULT NULL COMMENT '计费重量',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_waybill_number` (`waybill_number`),
  KEY `idx_flight_info` (`flight_info`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='南航订舱批复数据表';
