CREATE TABLE `peer_air_departure_manual_data` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `consignment_note_id` bigint(20) NOT NULL COMMENT '关联 consignment_notes.id',
  `waybill_number` varchar(100) DEFAULT NULL COMMENT '主单号',
  `customer_name` varchar(255) DEFAULT NULL COMMENT '客户名称',
  `cargo_type` varchar(50) DEFAULT NULL COMMENT '货物类型',
  `packaging_fee` varchar(50) DEFAULT NULL COMMENT '包装费',
  `telegram_fee` varchar(50) DEFAULT NULL COMMENT '电报费',
  `cca` varchar(50) DEFAULT NULL COMMENT 'CCA',
  `door_pickup_fee` varchar(50) DEFAULT NULL COMMENT '上门提货费',
  `door_pickup_company` varchar(255) DEFAULT NULL COMMENT '上门提货单位',
  `airport_pickup_fee` varchar(50) DEFAULT NULL COMMENT '机场提货费',
  `airport_pickup_company` varchar(255) DEFAULT NULL COMMENT '机场提货单位',
  `delivery_fee` varchar(50) DEFAULT NULL COMMENT '派送费',
  `delivery_company` varchar(255) DEFAULT NULL COMMENT '派送单位',
  `carrier_deduction` varchar(50) DEFAULT NULL COMMENT '承运扣款',
  `other_fees` varchar(50) DEFAULT NULL COMMENT '其他费用',
  `manual_total_amount` varchar(50) DEFAULT NULL COMMENT '总金额',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `audit_status` int(11) DEFAULT '0' COMMENT '审核状态: 0=未审, 1=暂存, 2=已审',
  `auditor_id` bigint(20) DEFAULT NULL COMMENT '审核人ID',
  `auditor_name` varchar(255) DEFAULT NULL COMMENT '审核人',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_peer_air_manual_consignment_id` (`consignment_note_id`),
  KEY `ix_peer_air_departure_manual_data_id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='同行空运出港扩展（手动/审核）数据表';
