CREATE TABLE IF NOT EXISTS `shenzhen_air_approval_wide_body_data` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `parent_id` BIGINT DEFAULT NULL COMMENT '父级ID，用于关联子项到父项',
    `flight_number` VARCHAR(50) DEFAULT NULL COMMENT '航班号',
    `flight_date` VARCHAR(50) DEFAULT NULL COMMENT '航班日期',
    `aircraft_type` VARCHAR(50) DEFAULT NULL COMMENT '机型',
    `departure_time` VARCHAR(50) DEFAULT NULL COMMENT '起飞',
    `routing` VARCHAR(100) DEFAULT NULL COMMENT '航程',
    `agent` VARCHAR(100) DEFAULT NULL COMMENT '代理人',
    `board_booking` VARCHAR(50) DEFAULT NULL COMMENT '板订',
    `board_approval` VARCHAR(50) DEFAULT NULL COMMENT '板批',
    `backup_board` VARCHAR(50) DEFAULT NULL COMMENT '备份板',
    `box_booking` VARCHAR(50) DEFAULT NULL COMMENT '箱订',
    `box_approval` VARCHAR(50) DEFAULT NULL COMMENT '箱批',
    `backup_box` VARCHAR(50) DEFAULT NULL COMMENT '备份箱',
    `status` VARCHAR(50) DEFAULT NULL COMMENT '状态',
    `type` VARCHAR(50) DEFAULT NULL COMMENT '类型',
    `remark` TEXT DEFAULT NULL COMMENT '备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    PRIMARY KEY (`id`),
    KEY `ix_shenzhen_air_approval_wide_body_data_id` (`id`),
    KEY `ix_shenzhen_air_approval_wide_body_data_parent_id` (`parent_id`),
    KEY `ix_shenzhen_air_approval_wide_body_data_flight_number` (`flight_number`),
    KEY `ix_shenzhen_air_approval_wide_body_data_flight_date` (`flight_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='深航订舱批复数据(宽体机)';
